[project]
name = "claimwise-ai"
version = "0.2.0"
description = "ClaimWise AI — Enterprise Copilot untuk Optimasi Triase Klaim & Alokasi Penjadwalan Verifikator Berbasis CSP & Algoritma Genetika"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Davina Olivia Yosefanny Hutabarat" },
    { name = "Pedro Simangunsong" },
    { name = "Jodi" }
]
keywords = [
    "artificial-intelligence",
    "constraint-satisfaction-problem",
    "ac-3-algorithm",
    "backtracking-mrv",
    "genetic-algorithm",
    "workforce-scheduling",
    "health-insurance",
    "state-space-search"
]
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[tool.uv]
package = false